language: node_js
nodejs:
  - "10"


jobs:
  include:
    - stage: test
      name: "Testing all components"
      script: 
        npm run test
    - stage: Build
      name: "Build with webpack"
      script: 
        npm run build
    - deploy:
        local_dir: dist
        github_token: $GH_TOKEN
        provider: pages
        skip_cleanup: true
        keep_history: true
        on:
          branch: gh-pages