language: node_js
nodejs:
  - "10"


jobs:
  include:
    - stage: test
      name: "Unit testing"
      script: 
        npm run test
        npm run test:coverage
    - stage: deploy
      name: "Deploy to gh-pages"
      script: 
        npm run build
        npm run build:docs
      deploy:
        local_dir: dist
        github_token: $GH_TOKEN
        provider: pages
        skip_cleanup: true
        keep_history: true
        on:
          branch: gh-pages