export default {
  userLogged: true,
  userHash: '',
  tagsAdded: false,
  locationAdded: false,
  ideas: '',
  places: '',
  selectedCountry: '',
  selectedCity: '',
  selectedZone: '',
  tagsToSend: '',
  leisureTags: ['hola', 'esto', 'va?'],
  lodgingTags: ['hola', 'esto', 'va?'],
  foodTags: ['hola', 'esto', 'va?', 'asd', 'asdasd', 'asdasdas'],
};
