export default {
  userLogged: true,
  userHash: '',
  tagsAdded: false,
  locationAdded: false,
  ideas: '',
  places: '',
  selectedCountry: '',
  selectedCity: '',
  selectedZone: '',
  tagsToSend: '',
  leisureTags: [],
  lodgingTags: [],
  foodTags: [],
};
